sudo: required

services:
    - docker

before_install:
    - docker pull cakephpfr/docs

script:
    - docker run -it --rm -v $(pwd):/data cakephpfr/docs:light make html SPHINXOPTS='-W'
    - docker run -it --rm -v $(pwd):/data cakephpfr/docs make epub SPHINXOPTS='-W'
    - docker run -it --rm -v $(pwd):/data cakephpfr/docs make latex SPHINXOPTS='-W'

notifications:
    email: false
