language: python

python:
 - "2.7"

install:
    - pip install -r requirements.txt
    - sudo apt-get install texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

script:
    - 'make html SPHINXOPTS="-W"'
    - 'make latex'
    - 'make epub'
    - 'make pdf'

notifications:
    email: false
