sudo: required

services:
  - docker

before_install:
  - docker pull cakephpfr/docs

script:
    - docker run -it --rm -v $(pwd):/data -p 127.0.0.1:80:4567 cakephpfr/docs make html SPHINXOPTS='-W'

notifications:
    email: false
